name: Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  goreleaser:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Release
        env:
          Version: $GITHUB_REF_NAME
          GITHUB_TOKEN: ${{ secrets.TRACE_MOE_GO_TOKEN }}
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
